### ISSUE TITLE
Is it compatible with Torch Nightly versions? 

### ISSUE THREAD

**Issue by MuhammadArham-Vyro** [chengzeyi/stable-fast#10]
I can not build Xformers from source. It crashes with OOM errors.

Installing stable-fast repository also results in erros when running setup.py.

Is there a workaround for this? It runs with torch2.1 but fails with nightly versions.

**Comment by chengzeyi** [comment]
> I can not build Xformers from source. It crashes with OOM errors.
> 
> Installing stable-fast repository also results in erros when running setup.py.
> 
> Is there a workaround for this? It runs with torch2.1 but fails with nightly versions.

Building `xformers` with OOM crashes is very common, you can limit the number of threads of the building task by setting the environment variable `MAX_JOBS` for `ninja` to avoid that.

Nightly versions of `PyTorch` are quite unstable. If you happen to see any errors, please provide detailed info in this thread.
