### ISSUE TITLE
compile_unet error for `StableDiffusionLatentUpscalePipeline`

### ISSUE THREAD

**Issue by kunc01** [chengzeyi/stable-fast#106]
Hi! Thanks for your amazing work. 

I've tested on a V100 GPU, stable-fast works perfect for `StableDiffusionControlNetInpaintPipeline`, but for [latent-upscaler](https://huggingface.co/stabilityai/sd-x2-latent-upscaler) and corresponding [StableDiffusionLatentUpscalePipeline](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_latent_upscale.py), `sfast.compilers.diffusion_pipeline_compiler.compile_unet` leads to 
<img width="934" alt="err" src="https://github.com/chengzeyi/stable-fast/assets/18576899/0c324fa8-f63f-4f92-b3d5-be9c8f09c554">
, while vae and text_encoder still work well. 

I've tried options like `enable_xformers`, `enable_triton`, `enable_cuda_graph`, `prefer_lowp_gemm` and `enable_fused_linear_geglu`, but the error persists.

Looking forward to your reply, thank you!

**Comment by chengzeyi** [comment]
@kunc01 This problem has been fixed in the latest nightly release. Please try it.

**Comment by kunc01** [comment]
@chengzeyi Thanks for your reply，I tried 1.0.2.dev20240127+torch211cu118 on a V100 and 1.0.2.dev20240127+torch211cu121 on a A10，but found new errors.
![error](https://github.com/chengzeyi/stable-fast/assets/18576899/de6eaded-779c-4731-af3f-e9cde62bfc03)

**Comment by chengzeyi** [comment]
> @chengzeyi Thanks for your reply，I tried 1.0.2.dev20240127+torch211cu118 on a V100 and 1.0.2.dev20240127+torch211cu121 on a A10，but found new errors. ![error](https://private-user-images.githubusercontent.com/18576899/300326766-de6eaded-779c-4731-af3f-e9cde62bfc03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDAwNjQsIm5iZiI6MTcwNjQ5OTc2NCwicGF0aCI6Ii8xODU3Njg5OS8zMDAzMjY3NjYtZGU2ZWFkZWQtNzc5Yy00NzMxLWFmM2YtZTljZGU2MmJmYzAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzNDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODIyNTYyMDZiNWQ4NDJjNTc5NTQxN2ZhYjdiMzQ2M2YwYjcxZjk5MDk5MmM1YTU1OWYyYjEwYzEwOGEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjrkWHfA3fMs1nAnMupAEpLlsu9yfYHDiX6bCb5QgnA)

Can you share a minimal reproducing script so that I can reproduce it on my machine?

**Comment by chengzeyi** [comment]
> @chengzeyi Thanks for your reply，I tried 1.0.2.dev20240127+torch211cu118 on a V100 and 1.0.2.dev20240127+torch211cu121 on a A10，but found new errors. ![error](https://private-user-images.githubusercontent.com/18576899/300326766-de6eaded-779c-4731-af3f-e9cde62bfc03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDAwNjQsIm5iZiI6MTcwNjQ5OTc2NCwicGF0aCI6Ii8xODU3Njg5OS8zMDAzMjY3NjYtZGU2ZWFkZWQtNzc5Yy00NzMxLWFmM2YtZTljZGU2MmJmYzAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzNDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODIyNTYyMDZiNWQ4NDJjNTc5NTQxN2ZhYjdiMzQ2M2YwYjcxZjk5MDk5MmM1YTU1OWYyYjEwYzEwOGEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjrkWHfA3fMs1nAnMupAEpLlsu9yfYHDiX6bCb5QgnA)

Just fixed it. Please retry.

**Comment by kunc01** [comment]
@chengzeyi 
![error](https://github.com/chengzeyi/stable-fast/assets/18576899/abdd47f2-401c-44c3-959a-1b2a6400f449)

**Comment by chengzeyi** [comment]
> @chengzeyi ![error](https://private-user-images.githubusercontent.com/18576899/300338479-abdd47f2-401c-44c3-959a-1b2a6400f449.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDY1NjAsIm5iZiI6MTcwNjUwNjI2MCwicGF0aCI6Ii8xODU3Njg5OS8zMDAzMzg0NzktYWJkZDQ3ZjItNDAxYy00NGMzLTk1OWEtMWIyYTY0MDBmNDQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA1MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ODYzZWMzNDI0NGJjYzZhODNlZmZhMjJjYzM2MGJmNWNhNGIxYzRlMTQzY2Q4MWNiOWU3ZDYwZWQ2ZWNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fJtFjJ1WZcG-6t7UbeN32mnpAMwlK2rbQ-f5h7ctGCM)

I guess this is related to Triton. can you try running with disabling Triton?

**Comment by kunc01** [comment]
@chengzeyi Inference succeeded with `enable_triton = False`

`upsampler = StableDiffusionLatentUpscalePipeline.from_pretrained("stabilityai/sd-x2-latent-upscaler", torch_dtype=torch.float16).to("cuda")`
`config = CompilationConfig.Default()`
`config.enable_xformers = True`
`config.enable_triton = False`
`config.enable_cuda_graph = True`
`upsampler = compile(upsampler, config)`
