### ISSUE TITLE
Optimizing Controlnets independently?

### ISSUE THREAD

**Issue by shawnrushefsky** [chengzeyi/stable-fast#11]
First, awesome work. The speed improvement is great, and the additional cold start time is very manageable.

Second, I load many pipelines for each model, and do things like swap out controlnets and vaes in response to user requests. When I swap controlnets and run a generation, I am getting the error `RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float`. I'm guessing this is because the replacement controlnet hasn't had the same optimizations as the original. Is there a way to compile just the controlnets so that they can be swapped in and out of the pipeline dynamically?

**Comment by chengzeyi** [comment]
> First, awesome work. The speed improvement is great, and the additional cold start time is very manageable.
> 
> Second, I load many pipelines for each model, and do things like swap out controlnets and vaes in response to user requests. When I swap controlnets and run a generation, I am getting the error `RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float`. I'm guessing this is because the replacement controlnet hasn't had the same optimizations as the original. Is there a way to compile just the controlnets so that they can be swapped in and out of the pipeline dynamically?

Hi, friend.

Technically speaking, ControlNet does not just serve as an independent module, but hijacks the UNet structure. So after switching the ControlNet, the forward graph of the UNet also needs to be recompiled. In conclusion, independent compilation of ControlNet is not possible.

However, if you want to reduce the compilation time of each loading, you can wrap your whole code block including compiling and inference into one `torch.jit.optimized_execution(False)` context manager to disable `nvfuser` code generation. You can also adjust the compilation config to disable `CUDA Graph Capture`.

```python
with torch.jit.optimized_execution(False):
    model = XXX.from_pretrained('xxx')
    model = compile(model, config)
    outputs = model(**kwarg_inputs)
```

**Comment by chengzeyi** [comment]
> First, awesome work. The speed improvement is great, and the additional cold start time is very manageable.
> 
> Second, I load many pipelines for each model, and do things like swap out controlnets and vaes in response to user requests. When I swap controlnets and run a generation, I am getting the error `RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float`. I'm guessing this is because the replacement controlnet hasn't had the same optimizations as the original. Is there a way to compile just the controlnets so that they can be swapped in and out of the pipeline dynamically?

I have made switching LoRA dynamically possible:
[https://github.com/chengzeyi/stable-fast#dynamically-switch-lora](https://github.com/chengzeyi/stable-fast#dynamically-switch-lora)

And switching controlnet dynamically should also be possible with `state_dict()` and `load_state_dict`, you could try yourself.
