### ISSUE TITLE
Save compiled model and reuse? 

### ISSUE THREAD

**Issue by alecyan1993** [chengzeyi/stable-fast#111]
Hi,

Thanks for the amazing work. Is there any way to save the compiled model and reuse it for the acceleration? Thanks!

**Comment by chengzeyi** [comment]
> Hi,
> 
> Thanks for the amazing work. Is there any way to save the compiled model and reuse it for the acceleration? Thanks!

That would quite complex since the compiled pipeline has many dynamic things. So my suggestion is to find ways to speedup the loading & compilation.

**Comment by alecyan1993** [comment]
thanks for the reply!

**Comment by TimPietrusky** [comment]
@chengzeyi Do you have any suggestions on how to speedup the compilation? Because this step takes the most amount of time, between 30 to 45 seconds. We tested with a 4090 and 3080, the compilation is almost the same on these.
