### ISSUE TITLE
get rid of OpenCV related deps, possible? 

### ISSUE THREAD

**Issue by wingmrc** [chengzeyi/stable-fast#113]
I am using stable-fast with comfyui and other custom nodes. its always giving me cv2 related errors.
as cv2 has variations such as `opencv-python` `opencv-python-headless` `opencv-contrib-python` `opencv-contrib-python-headless` which are required by many other nodes for many versions.  

here is a sample of sfast related error.
```
ages\Python310\site-packages\sfast\utils\env.py", line 74, in _configure_libraries
    cv2.ocl.setUseOpenCL(False)
AttributeError: module 'cv2.ocl' has no attribute 'setUseOpenCL'
```
just wondering if it is possible to remove opencv deps.

**Comment by chengzeyi** [comment]
@wingmrc This has been fixed in the latest main branch. However, the CI is broken now due to shortage of disk space so please download and compile yourself.
