### ISSUE TITLE
ModuleNotFoundError: No module named 'sfast._C'

### ISSUE THREAD

**Issue by dushwe** [chengzeyi/stable-fast#12]
Traceback (most recent call last):
  File "/workspace/webui-pakage/stable-fast-0.0.2/predict.py", line 3, in <module>
    from sfast.compilers.stable_diffusion_pipeline_compiler import (compile,
  File "/workspace/webui-pakage/stable-fast-0.0.2/sfast/__init__.py", line 22, in <module>
    import sfast._C as _C
ModuleNotFoundError: No module named 'sfast._C'

how to solve? 

env:
  A100
  xformers                0.0.22.post4+cu118
  triton                  2.1.0
  torch                   2.1.0+cu118
 transformers            4.34.1
 ninja                   1.11.1.1
diffusers               0.21.4
stable-fast             0.0.2

**Comment by chengzeyi** [comment]
> Traceback (most recent call last):
> 
>   File "/workspace/webui-pakage/stable-fast-0.0.2/predict.py", line 3, in <module>
> 
>     from sfast.compilers.stable_diffusion_pipeline_compiler import (compile,
> 
>   File "/workspace/webui-pakage/stable-fast-0.0.2/sfast/__init__.py", line 22, in <module>
> 
>     import sfast._C as _C
> 
> ModuleNotFoundError: No module named 'sfast._C'
> 
> 
> 
> how to solve? 
> 
> 
> 
> env:
> 
>   A100
> 
>   xformers                0.0.22.post4+cu118
> 
>   triton                  2.1.0
> 
>   torch                   2.1.0+cu118
> 
>  transformers            4.34.1
> 
>  ninja                   1.11.1.1
> 
> diffusers               0.21.4
> 
> stable-fast             0.0.2
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Do you build the package following my instructions in README.md?

**Comment by dushwe** [comment]
> > Traceback (most recent call last):
> > File "/workspace/webui-pakage/stable-fast-0.0.2/predict.py", line 3, in 
> > ```
> > from sfast.compilers.stable_diffusion_pipeline_compiler import (compile,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/workspace/webui-pakage/stable-fast-0.0.2/sfast/**init**.py", line 22, in 
> > ```
> > import sfast._C as _C
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ModuleNotFoundError: No module named 'sfast._C'
> > how to solve?
> > env:
> > A100
> > xformers                0.0.22.post4+cu118
> > triton                  2.1.0
> > torch                   2.1.0+cu118
> > transformers            4.34.1
> > ninja                   1.11.1.1
> > diffusers               0.21.4
> > stable-fast             0.0.2
> 
> Do you build the package following my instructions in README.md?

build the packpage  From Source

  cd stable-fast
  python setup.py bdist_wheel
  pip install dist/*.whl --force-reinstall

**Comment by chengzeyi** [comment]
Do you execute your script in the same directory of the repository? If so, please change to another directory.

If you still need to execute in the same directory, you should use a development build (pip install -e .).

**Comment by dushwe** [comment]
> Do you execute your script in the same directory of the repository? If so, please change to another directory.
> 
> If you still need to execute in the same directory, you should use a development build (pip install -e .).
thank you ！

**Comment by lengyanju8** [comment]
(py310) D:\sd\stable-fast>pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///D:/sd/stable-fast
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lengyanju8** [comment]
stable-fast/src/sfast/jit/overrides.py:21: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return func(*args, **kwargs)
段错误 (核心已转储)
why 
pytorch 2.1.1
stable-fast 1.0.1
Editable project location: /home/stable-fast/src
Requires: torch
