### ISSUE TITLE
Distribute pre-compiled wheels

### ISSUE THREAD

**Issue by isidentical** [chengzeyi/stable-fast#13]
Since the setup is very peculiar and computationally intensive (and also requires cudnn/cublas on the target machine), would it make sense to distribute/attach wheels with releases?

**Comment by chengzeyi** [comment]
Currently end users have to tackle with building from scratch. I would try to build a GitHub workflow to distribute binary releases for recent PyTorch and CUDA versions.

**Comment by chengzeyi** [comment]
> Since the setup is very peculiar and computationally intensive (and also requires cudnn/cublas on the target machine), would it make sense to distribute/attach wheels with releases?

CI has been successfully built. Binary wheels are now available at [https://github.com/chengzeyi/stable-fast/releases](https://github.com/chengzeyi/stable-fast/releases)
