### ISSUE TITLE
Changing working device will cause problem

### ISSUE THREAD

**Issue by xiyanjoy** [chengzeyi/stable-fast#139]
[stable_fast_test.txt](https://github.com/chengzeyi/stable-fast/files/14896895/stable_fast_test.txt)
In the presented example, the model is working on the 'cuda' by default. However, if I change the working device to 'cuda:7' as shown in the attach code, there would be some weird problem.
[error.txt](https://github.com/chengzeyi/stable-fast/files/14896942/error.txt)
How do I solve this problem?

**Comment by xiyanjoy** [comment]
Or is there somebody working well in a different device? Look forward to seeing your code!

**Comment by zhangvia** [comment]
you can use export CUDA_VISIBLE_DEVICES=7 to set device id

**Comment by xiyanjoy** [comment]
> you can use export CUDA_VISIBLE_DEVICES=7 to set device id
It works! Thanks bro.
