### ISSUE TITLE
LCM compatible? 

### ISSUE THREAD

**Issue by radames** [chengzeyi/stable-fast#14]
What would make it compatible with LCM models?
https://github.com/luosiallen/latent-consistency-model

**Comment by chengzeyi** [comment]
Looks like LCM is getting more popular today, it worths a try.

**Comment by SuperSecureHuman** [comment]
I am testing it with LCM

17its/s (8 steps) when compiled

I'll give some proper numbers when I have some more time

**Comment by chengzeyi** [comment]
LCM is officially supported now.

https://github.com/chengzeyi/stable-fast/blob/45c96aae240ff1d6338390d6f0471759688fa3e6/examples/optimize_lcm_pipeline.py
