### ISSUE TITLE
RuntimeError for Demo Test

### ISSUE THREAD

**Issue by alecyan1993** [chengzeyi/stable-fast#15]
Hi, 

Thanks for your work. I am running the demo test but having this issue when running the inference after successful compile: 
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):

graph(%1, %2):
    %x : Tensor = sfast_triton::reshape(%1, %2)
                  ~~~~~~~~~~~~ <--- HERE
    return (%x)
RuntimeError: RuntimeError: shape '[512, 512, 64, 64]' is invalid for input of size 2097152

At:
  /opt/sd/lib/python3.10/site-packages/torch/_ops.py(502): __call__
  /opt/sd/lib/python3.10/site-packages/sfast/triton/torch_ops.py(82): forward
  /opt/sd/lib/python3.10/site-packages/torch/autograd/function.py(506): apply
  /opt/sd/lib/python3.10/site-packages/sfast/triton/torch_ops.py(97): reshape
  /opt/sd/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
  /opt/sd/lib/python3.10/site-packages/sfast/jit/trace_helper.py(111): forward
  /opt/sd/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
  /opt/sd/lib/python3.10/site-packages/sfast/jit/trace_helper.py(57): wrapper
  /opt/sd/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py(707): __call__
  /opt/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py(115): decorate_context
  /hostroot/experiments/sfast/test_sfast.py(70): <module>
```

Would you help to have a look? Thanks!

**Comment by chengzeyi** [comment]
> Hi,
> 
> Thanks for your work. I am running the demo test but having this issue when running the inference after successful compile:
> 
> ```
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> 
> graph(%1, %2):
>     %x : Tensor = sfast_triton::reshape(%1, %2)
>                   ~~~~~~~~~~~~ <--- HERE
>     return (%x)
> RuntimeError: RuntimeError: shape '[512, 512, 64, 64]' is invalid for input of size 2097152
> 
> At:
>   /opt/sd/lib/python3.10/site-packages/torch/_ops.py(502): __call__
>   /opt/sd/lib/python3.10/site-packages/sfast/triton/torch_ops.py(82): forward
>   /opt/sd/lib/python3.10/site-packages/torch/autograd/function.py(506): apply
>   /opt/sd/lib/python3.10/site-packages/sfast/triton/torch_ops.py(97): reshape
>   /opt/sd/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
>   /opt/sd/lib/python3.10/site-packages/sfast/jit/trace_helper.py(111): forward
>   /opt/sd/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
>   /opt/sd/lib/python3.10/site-packages/sfast/jit/trace_helper.py(57): wrapper
>   /opt/sd/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py(707): __call__
>   /opt/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py(115): decorate_context
>   /hostroot/experiments/sfast/test_sfast.py(70): <module>
> ```
> 
> Would you help to have a look? Thanks!

Can you share the version of `diffusers` library you use?

**Comment by alecyan1993** [comment]
Hi, 
Thanks for the reply! Here's the version of the diffusers that I am using: `diffusers==0.21.4`
I installed the stable-fast 0.0.5 instead of 0.0.6 and it works.

**Comment by chengzeyi** [comment]
> Hi, Thanks for the reply! Here's the version of the diffusers that I am using: `diffusers==0.21.4` I installed the stable-fast 0.0.5 instead of 0.0.6 and it works.

This should be a bug related to tracing VAE.decode in the pipeline.
I have fixed this in the `main` branch and you can update it.

**Comment by alecyan1993** [comment]
Thanks! Another issue that I found is it's not accelerating SDXL. I'm running the demo with A100, the speed of SDXL for the compiled model is 5.3 it/s but with normal diffusers it's 8.8 it/s. The compiled one with stable-fast  is slower.

**Comment by chengzeyi** [comment]
> Thanks! Another issue that I found is it's not accelerating SDXL. I'm running the demo with A100, the speed of SDXL for the compiled model is 5.3 it/s but with normal diffusers it's 8.8 it/s. The compiled one with stable-fast is slower.

Can you try to disable CUDA Graph or disable Triton?
I have no A100 resources available so it's hard to debug.

**Comment by alecyan1993** [comment]
yeah will have a try, thanks!
