### ISSUE TITLE
Invert FORCE_CUDA=1 or improve install from source to fail if cuda extensions can't be built

### ISSUE THREAD

**Issue by skirsten** [chengzeyi/stable-fast#32]
So I was debugging why the deployed model inference was slower than in a Jupyter Notebook. 
The reason was that the CI that is building the container image did not build the cuda extensions (because of [this](https://github.com/chengzeyi/stable-fast/blob/2ddea8f9f1e3a6153289407db4858d69c1dda948/setup.py#L74-L76)).

It would probably be better to invert this logic to throw an error if It cannot build the cuda extensions.
Otherwise many users might not understand why their performance is worse than what should be possible.

This could be bypassed with a env var like `OPTIONAL_CUDA=1` or `DISABLE_CUDA=1`.

**Comment by chengzeyi** [comment]
An new environment variable `WITHOUT_CUDA` has been added, fails if CUDA is not available and that is not set.

**Comment by chengzeyi** [comment]
Looks like the previously built wheel packages are all without CUDA and CUDNN😂.
I am refactoring `setup.py` to correctly include those things. I am trying to use the bundled CUDNN with PyTorch from the `nvidia.cudnn` package as it seems that most users don't have a system-installed CUDNN.

**Comment by skirsten** [comment]
> Looks like the previously built wheel packages are all without CUDA and CUDNN😂.

:sweat_smile: 

> I am trying to use the bundled CUDNN with PyTorch from the nvidia.cudnn package as it seems that most users don't have a system-installed CUDNN.

Awesome, that should make it more portable and easy to install :+1:
