### ISSUE TITLE
[Enhancement] Contribution to A100 numbers

### ISSUE THREAD

**Issue by SuperSecureHuman** [chengzeyi/stable-fast#39]
Hey!

I have access to A100s, and would like to submit the results from A100. Let me know if you have some sort of benchmark script up and ready so that I can use it to run and get the numbers.

**Comment by chengzeyi** [comment]
Hello @SuperSecureHuman 

Very glad that you could give a help!

If you want to help benchmark, you could follow the below instructions:

```bash
git clone https://github.com/chengzeyi/stable-fast.git
cd stable-fast
# clone third-party dependencies
git submodule update --init --update

# install build dependencies
pip3 install torch torchvision torchaudio ninja

pip3 install -e '.[dev,xformers,triton,transformers,diffusers]' -v

# install TCMalloc to reduce CPU overhead
sudo apt install -y libtcmalloc-minimal4
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4

# run benchmarks
python3 -m pytest tests/compilers/test_stable_diffusion_pipeline_compiler.py::test_benchmark_sd15_model
python3 -m pytest tests/compilers/test_stable_diffusion_pipeline_compiler.py::test_benchmark_sd21_model
python3 -m pytest 
tests/compilers/test_stable_diffusion_pipeline_compiler.py::test_benchmark_sdxl_model
python3 -m pytest tests/compilers/test_stable_diffusion_pipeline_compiler.py::test_benchmark_sd15_model_with_controlnet
python3 -m pytest tests/compilers/test_stable_diffusion_pipeline_compiler.py::test_benchmark_sd15_model_with_lora

# tell me your system configuration
python3 -m torch.utils.collect_env

# tell me your current version of stable-fast
git status
```

The current benchmarking results are expected to be slower than real deployment environments because I have to call `torch.cuda.synchronize()` repeatedly to make the status bar display correctly.

**Comment by SuperSecureHuman** [comment]
SD 1.5

<details>
<summary>Details</summary>

```
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|           Caller           | Caller time | Number of calls | Total time | Cumulative time |                                   Callee                                   |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|    call_original_model     |    1.496    |        1        |   0.000    |      1.496      |    test_stable_diffusion_pipeline_compiler.py:271(call_original_model)     |
|                            |             |        1        |   0.000    |      1.496      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.496      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.003    |      1.496      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |      20390      |   0.031    |      1.429      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |      20390      |   0.067    |      1.429      |                         module.py:1520(_call_impl)                         |
|                            |             |        30       |   0.006    |      1.395      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |       480       |   0.030    |      0.817      |                       transformer_2d.py:240(forward)                       |
|                            |             |        90       |   0.005    |      0.695      |                      unet_2d_blocks.py:2288(forward)                       |
|                            |             |       480       |   0.043    |      0.620      |                         attention.py:216(forward)                          |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_torch_compiled_model  |    0.904    |        1        |   0.000    |      1.097      | test_stable_diffusion_pipeline_compiler.py:292(call_torch_compiled_model)  |
|                            |             |        1        |   0.000    |      1.097      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.096      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      1.096      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |       500       |   0.001    |      1.026      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       500       |   0.002    |      1.026      |                         module.py:1520(_call_impl)                         |
|                            |             |        60       |   0.001    |      0.990      |                           eval_frame.py:307(_fn)                           |
|                            |             |        30       |   0.000    |      0.980      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |        30       |   0.000    |      0.979      |                        external_utils.py:15(inner)                         |
|                            |             |        30       |   0.000    |      0.979      |                       aot_autograd.py:3901(forward)                        |
|                            |             |        30       |   0.000    |      0.979      |                          aot_autograd.py:1481(g)                           |
|                            |             |        30       |   0.000    |      0.978      |                   aot_autograd.py:2519(runtime_wrapper)                    |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    0.681    |        1        |   0.000    |      0.685      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      0.685      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.685      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.003    |      0.685      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |        31       |   0.000    |      0.544      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.542    |      0.542      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.538      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |        68       |   0.000    |      0.108      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |        68       |   0.026    |      0.108      |                         module.py:1520(_call_impl)                         |
|                            |             |        3        |   0.000    |      0.091      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        3        |   0.000    |      0.091      |                        trace_helper.py:110(forward)                        |
|                            |             |        1        |   0.000    |      0.071      |              pipeline_stable_diffusion.py:261(encode_prompt)               |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
PASSED
```

</details>

| **Method**         | **T1**     | **T2**     | **T3**     | **T4**     | **AVG(T2,T3,T4)** |
|----------------|--------|--------|--------|--------|---------------|
| Original       | 14.83it/s  | 24.01it/s  | 23.78it/s  | 21.15it/s  | 22.98it/s         |
| torch.compile  | 3.06s/it   | 37.09it/s  | 37.65it/s  | 29.52it/s  | 34.75it/s         |
| Stable Fast    | 1.32it/s   | 49.47it/s  | 53.20it/s  | 53.07it/s  | 51.91it/s         |



---

SD 2.1

<details>
<summary>Details</summary>

+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|           Caller           | Caller time | Number of calls | Total time | Cumulative time |                                   Callee                                   |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|    call_original_model     |    1.489    |        1        |   0.000    |      1.489      |    test_stable_diffusion_pipeline_compiler.py:271(call_original_model)     |
|                            |             |        1        |   0.000    |      1.489      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.489      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.003    |      1.489      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |      20654      |   0.030    |      1.419      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |      20654      |   0.068    |      1.419      |                         module.py:1520(_call_impl)                         |
|                            |             |        30       |   0.006    |      1.366      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |       480       |   0.028    |      0.784      |                       transformer_2d.py:240(forward)                       |
|                            |             |        90       |   0.005    |      0.674      |                      unet_2d_blocks.py:2288(forward)                       |
|                            |             |       480       |   0.041    |      0.600      |                         attention.py:216(forward)                          |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_torch_compiled_model  |    0.830    |        1        |   0.000    |      0.993      | test_stable_diffusion_pipeline_compiler.py:292(call_torch_compiled_model)  |
|                            |             |        1        |   0.000    |      0.993      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.993      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      0.993      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |       764       |   0.001    |      0.922      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       764       |   0.003    |      0.922      |                         module.py:1520(_call_impl)                         |
|                            |             |        60       |   0.001    |      0.867      |                           eval_frame.py:307(_fn)                           |
|                            |             |        30       |   0.000    |      0.857      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |        30       |   0.000    |      0.856      |                        external_utils.py:15(inner)                         |
|                            |             |        30       |   0.000    |      0.856      |                       aot_autograd.py:3901(forward)                        |
|                            |             |        30       |   0.000    |      0.856      |                          aot_autograd.py:1481(g)                           |
|                            |             |        30       |   0.000    |      0.856      |                   aot_autograd.py:2519(runtime_wrapper)                    |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    0.703    |        1        |   0.000    |      0.710      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      0.710      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.710      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.003    |      0.710      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |        31       |   0.000    |      0.512      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.510    |      0.510      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.510      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |        68       |   0.000    |      0.161      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |        68       |   0.040    |      0.161      |                         module.py:1520(_call_impl)                         |
|                            |             |        3        |   0.000    |      0.144      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        3        |   0.000    |      0.144      |                        trace_helper.py:110(forward)                        |
|                            |             |        1        |   0.000    |      0.124      |              pipeline_stable_diffusion.py:261(encode_prompt)               |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+

</details>

| **Method**         | **T1**     | **T2**     | **T3**     | **T4**     | **AVG(T2,T3,T4)** |
|----------------|--------|--------|--------|--------|---------------|
| Original       | 15.05it/s  | 23.90it/s  | 23.82it/s  | 21.53it/s  | 23.08it/s         |
| torch.compile  | 2.91s/it   | 42.24it/s  | 42.67it/s  | 33.61it/s  | 39.51it/s         |
| Stable Fast    | 1.50it/s   | 55.92it/s  | 55.94it/s  | 55.85it/s  | 55.90it/s         |

---

SDXL

<details>
<summary>Details</summary>

+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|           Caller           | Caller time | Number of calls | Total time | Cumulative time |                                   Callee                                   |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|    call_original_model     |    3.586    |        1        |   0.000    |      3.586      |    test_stable_diffusion_pipeline_compiler.py:271(call_original_model)     |
|                            |             |        1        |   0.000    |      3.586      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      3.586      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.003    |      3.586      |               pipeline_stable_diffusion_xl.py:699(__call__)                |
|                            |             |      52431      |   0.077    |      3.477      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |      52431      |   0.180    |      3.477      |                         module.py:1520(_call_impl)                         |
|                            |             |        30       |   0.006    |      3.423      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |       330       |   0.031    |      2.946      |                       transformer_2d.py:240(forward)                       |
|                            |             |       2100      |   0.191    |      2.780      |                         attention.py:216(forward)                          |
|                            |             |        60       |   0.004    |      1.685      |                      unet_2d_blocks.py:2288(forward)                       |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_torch_compiled_model  |    1.653    |        1        |   0.000    |      1.918      | test_stable_diffusion_pipeline_compiler.py:292(call_torch_compiled_model)  |
|                            |             |        1        |   0.000    |      1.918      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.918      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      1.918      |               pipeline_stable_diffusion_xl.py:699(__call__)                |
|                            |             |       741       |   0.001    |      1.814      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       741       |   0.004    |      1.814      |                         module.py:1520(_call_impl)                         |
|                            |             |        60       |   0.001    |      1.760      |                           eval_frame.py:307(_fn)                           |
|                            |             |        30       |   0.000    |      1.750      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |        30       |   0.000    |      1.749      |                        external_utils.py:15(inner)                         |
|                            |             |        30       |   0.000    |      1.749      |                       aot_autograd.py:3901(forward)                        |
|                            |             |        30       |   0.001    |      1.748      |                          aot_autograd.py:1481(g)                           |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    1.166    |        1        |   0.000    |      1.168      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      1.168      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.168      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      1.168      |               pipeline_stable_diffusion_xl.py:699(__call__)                |
|                            |             |        31       |   0.000    |      0.985      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.984    |      0.984      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.970      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |       457       |   0.001    |      0.123      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       457       |   0.020    |      0.122      |                         module.py:1520(_call_impl)                         |
|                            |             |        1        |   0.000    |      0.071      |             pipeline_stable_diffusion_xl.py:224(encode_prompt)             |
|                            |             |        2        |   0.000    |      0.056      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        2        |   0.000    |      0.056      |                        trace_helper.py:110(forward)                        |
|                            |             |       164       |   0.001    |      0.037      |                           function.py:534(apply)                           |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+

</details>


| **Method**         | **T1**     | **T2**     | **T3**     | **T4**     | **AVG(T2,T3,T4)** |
|----------------|--------|--------|--------|--------|---------------|
| Original       | 8.04it/s   | 9.98it/s   | 9.97it/s   | 8.69it/s   | 9.55it/s          |
| torch.compile  | 4.53s/it   | 20.13it/s  | 20.89it/s  | 16.78it/s  | 19.27it/s         |
| Stable Fast    | 1.90s/it   | 28.60it/s  | 29.62it/s  | 29.54it/s  | 29.25it/s         |

---

SD 1.5 Control Net

<details>
<summary>Details</summary>

+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|           Caller           | Caller time | Number of calls | Total time | Cumulative time |                                   Callee                                   |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|    call_original_model     |    2.209    |        1        |   0.000    |      2.209      |    test_stable_diffusion_pipeline_compiler.py:271(call_original_model)     |
|                            |             |        1        |   0.000    |      2.209      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      2.209      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      2.209      |                    pipeline_controlnet.py:729(__call__)                    |
|                            |             |      29900      |   0.051    |      2.133      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |      29900      |   0.106    |      2.133      |                         module.py:1520(_call_impl)                         |
|                            |             |        30       |   0.010    |      1.419      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |       690       |   0.042    |      1.198      |                       transformer_2d.py:240(forward)                       |
|                            |             |       180       |   0.007    |      0.916      |                      unet_2d_blocks.py:1115(forward)                       |
|                            |             |       690       |   0.062    |      0.911      |                         attention.py:216(forward)                          |
|                            |             |        90       |   0.005    |      0.704      |                      unet_2d_blocks.py:2288(forward)                       |
|                            |             |       974       |   0.122    |      0.694      |                           resnet.py:685(forward)                           |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_torch_compiled_model  |    1.354    |        1        |   0.000    |      1.658      | test_stable_diffusion_pipeline_compiler.py:292(call_torch_compiled_model)  |
|                            |             |        1        |   0.000    |      1.658      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.658      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.005    |      1.658      |                    pipeline_controlnet.py:729(__call__)                    |
|                            |             |       560       |   0.001    |      1.576      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       560       |   0.004    |      1.576      |                         module.py:1520(_call_impl)                         |
|                            |             |       120       |   0.002    |      1.538      |                           eval_frame.py:307(_fn)                           |
|                            |             |        60       |   0.000    |      1.517      |                        external_utils.py:15(inner)                         |
|                            |             |        60       |   0.000    |      1.517      |                       aot_autograd.py:3901(forward)                        |
|                            |             |        60       |   0.001    |      1.516      |                          aot_autograd.py:1481(g)                           |
|                            |             |        60       |   0.000    |      1.515      |                   aot_autograd.py:2519(runtime_wrapper)                    |
|                            |             |        60       |   0.001    |      1.515      |                 aot_autograd.py:1498(call_func_with_args)                  |
|                            |             |        60       |   0.000    |      1.514      |            aot_autograd.py:1583(rng_functionalization_wrapper)             |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    0.936    |        1        |   0.000    |      0.941      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      0.941      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.940      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.005    |      0.940      |                    pipeline_controlnet.py:729(__call__)                    |
|                            |             |        31       |   0.000    |      0.729      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.727    |      0.727      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.725      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |       128       |   0.000    |      0.165      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       128       |   0.029    |      0.165      |                         module.py:1520(_call_impl)                         |
|                            |             |        3        |   0.000    |      0.092      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        3        |   0.000    |      0.091      |                        trace_helper.py:110(forward)                        |
|                            |             |        60       |   0.000    |      0.073      |                   graphs.py:18(dynamic_graphed_callable)                   |
|                            |             |        1        |   0.000    |      0.071      |                 pipeline_controlnet.py:250(encode_prompt)                  |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+

</details>

| **Method**         | **T1**     | **T2**     | **T3**     | **T4**     | **AVG(T2,T3,T4)** |
|----------------|--------|--------|--------|--------|---------------|
| Original       | 11.08it/s  | 15.49it/s  | 15.71it/s  | 14.13it/s  | 15.11it/s         |
| torch.compile  | 3.91s/it   | 24.49it/s  | 24.71it/s  | 19.13it/s  | 22.78it/s         |
| Stable Fast    | 1.26it/s   | 37.08it/s  | 37.08it/s  | 37.04it/s  | 37.07it/s         |


---

SD 1.5 LORA

<details>
<summary>Details</summary>
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|           Caller           | Caller time | Number of calls | Total time | Cumulative time |                                   Callee                                   |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
|    call_original_model     |    2.008    |        1        |   0.000    |      2.008      |    test_stable_diffusion_pipeline_compiler.py:271(call_original_model)     |
|                            |             |        1        |   0.000    |      2.008      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      2.008      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      2.008      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |      31910      |   0.041    |      1.940      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |      31910      |   0.104    |      1.940      |                         module.py:1520(_call_impl)                         |
|                            |             |        30       |   0.006    |      1.905      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |       480       |   0.029    |      1.323      |                       transformer_2d.py:240(forward)                       |
|                            |             |       480       |   0.038    |      1.124      |                         attention.py:216(forward)                          |
|                            |             |        90       |   0.005    |      0.978      |                      unet_2d_blocks.py:2288(forward)                       |
|                            |             |       961       |   0.008    |      0.868      |                    attention_processor.py:496(forward)                     |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_torch_compiled_model  |    1.232    |        1        |   0.000    |      1.461      | test_stable_diffusion_pipeline_compiler.py:292(call_torch_compiled_model)  |
|                            |             |        1        |   0.000    |      1.461      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      1.461      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      1.461      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |       500       |   0.001    |      1.391      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |       500       |   0.003    |      1.390      |                         module.py:1520(_call_impl)                         |
|                            |             |        60       |   0.001    |      1.354      |                           eval_frame.py:307(_fn)                           |
|                            |             |        30       |   0.000    |      1.343      |                     unet_2d_condition.py:797(forward)                      |
|                            |             |        30       |   0.000    |      1.342      |                        external_utils.py:15(inner)                         |
|                            |             |        30       |   0.000    |      1.342      |                       aot_autograd.py:3901(forward)                        |
|                            |             |        30       |   0.000    |      1.341      |                          aot_autograd.py:1481(g)                           |
|                            |             |        30       |   0.000    |      1.341      |                   aot_autograd.py:2519(runtime_wrapper)                    |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    0.771    |        1        |   0.000    |      0.775      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      0.775      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.775      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      0.775      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |        31       |   0.000    |      0.624      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.622    |      0.622      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.619      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |        68       |   0.000    |      0.117      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |        68       |   0.029    |      0.117      |                         module.py:1520(_call_impl)                         |
|                            |             |        3        |   0.000    |      0.092      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        3        |   0.000    |      0.092      |                        trace_helper.py:110(forward)                        |
|                            |             |        1        |   0.000    |      0.072      |              pipeline_stable_diffusion.py:261(encode_prompt)               |
|             *              |      *      |        *        |     *      |        *        |                                     *                                      |
| call_faster_compiled_model |    0.804    |        1        |   0.000    |      0.809      | test_stable_diffusion_pipeline_compiler.py:337(call_faster_compiled_model) |
|                            |             |        1        |   0.000    |      0.809      |         test_stable_diffusion_pipeline_compiler.py:155(call_model)         |
|                            |             |        1        |   0.000    |      0.809      |                    _contextlib.py:112(decorate_context)                    |
|                            |             |        1        |   0.004    |      0.809      |                 pipeline_stable_diffusion.py:635(__call__)                 |
|                            |             |        31       |   0.000    |      0.654      |                        __init__.py:773(synchronize)                        |
|                            |             |        31       |   0.652    |      0.652      |                {built-in method torch._C._cuda_synchronize}                |
|                            |             |        30       |   0.000    |      0.650      |      test_stable_diffusion_pipeline_compiler.py:245(scheduler_step_)       |
|                            |             |        68       |   0.000    |      0.117      |                     module.py:1514(_wrapped_call_impl)                     |
|                            |             |        68       |   0.027    |      0.117      |                         module.py:1520(_call_impl)                         |
|                            |             |        3        |   0.000    |      0.091      |                        trace_helper.py:39(wrapper)                         |
|                            |             |        3        |   0.000    |      0.090      |                        trace_helper.py:110(forward)                        |
|                            |             |        1        |   0.000    |      0.070      |              pipeline_stable_diffusion.py:261(encode_prompt)               |
+----------------------------+-------------+-----------------+------------+-----------------+----------------------------------------------------------------------------+
</details>

| **Method**         | **T1**     | **T2**     | **T3**     | **T4**     | **AVG(T2,T3,T4)** |
|----------------|--------|--------|--------|--------|---------------|
| Original       | 12.03it/s  | 17.26it/s  | 17.40it/s  | 15.54it/s  | 16.73it/s         |
| torch.compile  | 3.15s/it   | 27.72it/s  | 27.56it/s  | 21.74it/s  | 25.67it/s         |
| Stable Fast    | 1.29it/s   | 46.02it/s  | 46.02it/s  | 45.86it/s  | 45.97it/s         |

---

**Comment by SuperSecureHuman** [comment]
Here are the numbers

T1 - First Iteration Time

T2 to T4 - Actual Runs

Then there is average


Details has the table that was output

**Comment by chengzeyi** [comment]
> Here are the numbers
> 
> 
> 
> T1 - First Iteration Time
> 
> 
> 
> T2 to T4 - Actual Runs
> 
> 
> 
> Then there is average
> 
> 
> 
> 
> 
> Details has the table that was output

Great job!

Can you comment out the torch.cuda.synchronize statement in the test script and rerun and provide your detailed system configuration by running collect_env? I need to know the influence of stream synchronization and subtract it from the results. I also need to know your version of A100. Does it has 40GB VRAM or 80GB?

**Comment by chengzeyi** [comment]
We have 2 lines of `torch.cuda.synchronize` in the test script. It has a 3%-5% negative influence on performance.
After commenting out, the status bar will work incorrectly for `stable-fast compile`, but the table will tell us.😀

**Comment by SuperSecureHuman** [comment]
I'll try and get back.

It's a 40gb variant from Colab Pro

**Comment by SuperSecureHuman** [comment]
Git Commit was - https://github.com/chengzeyi/stable-fast/commit/2cf3b7662ebaf8e2f016952385272171ea5ada98

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        7
BogoMIPS:                        4400.31
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        6 MiB (6 instances)
L3 cache:                        38.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchdata==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect
```

**Comment by SuperSecureHuman** [comment]
I can run this on a100 80gb bare metal, but might take some time, (maybe even long, due to shipping issues)

I'll reopen this issue when I have those results
