### ISSUE TITLE
Openai triton conv kernel can't run correctly

### ISSUE THREAD

**Issue by wz0424** [chengzeyi/stable-fast#41]
I'm running the triton version of conv from the repository under triton version 2.1.0, and single-step debugging revealed that the problem should be that I can't lanuch the conv kernel. Once I run the portion of the program that lanuch the kernel, it's automatically killed. What is the problem?
![20231120-113647](https://github.com/chengzeyi/stable-fast/assets/51048934/206395e4-890e-468b-bda0-320841f54a71)

**Comment by chengzeyi** [comment]
> I'm running the triton version of conv from the repository under triton version 2.1.0, and single-step debugging revealed that the problem should be that I can't lanuch the conv kernel. Once I run the portion of the program that lanuch the kernel, it's automatically killed. What is the problem? ![20231120-113647](https://user-images.githubusercontent.com/51048934/284122859-206395e4-890e-468b-bda0-320841f54a71.jpeg)

Well, this convolution implementation uses prefetch techniques to speed up. However, the current Triton has bugs of analyzing the pattern of prefetch operations and triggers segmentation fault.

So that's why this conv operator is disabled.

**Comment by wz0424** [comment]
Thanks for your answer, I ran it successfully in triton version 2.1.0.post20231118001511, but it seems to be a bit of a metaphysics, the same version of triton on a different server still reports errors. Anyway finally no problem!😂

**Comment by chengzeyi** [comment]
> Thanks for your answer, I ran it successfully in triton version 2.1.0.post20231118001511, but it seems to be a bit of a metaphysics, the same version of triton on a different server still reports errors. Anyway finally no problem!😂

Yes, Triton is very unstable. So I am currently thinking about implementing new kernel that requires GEMM operations with other techniques like CUDNN frontend and CUTLASS, while using Triton to implement other kernels like norm and reshape.

I just implemented a new `quantized::linear_dynamic` kernel with CUTLASS 3.3. It will be announced publicly later as an effective way of reducing memory requirement.
