### ISSUE TITLE
What's the advance compared to TensorRT?

### ISSUE THREAD

**Issue by AsakusaRinne** [chengzeyi/stable-fast#59]
Thank you for this great work. It's amazing that it could reach almost same performance with TensorRT on N-GPU!

However, is there a convincing reason of using it instead of TensorRT?

**Comment by chengzeyi** [comment]
In fact, so many reasons!
Here are some:

- Fastest compilation: Just cold start your whole pipeline in 10s, hundreds of times faster than TRT.
- Better support for various models: Support all SD models even latest LCM and SD Turbo, Which TRT does not support well.
- Open sourced and can be migrated to other platforms: AMD GPUs can also be supported in theory. This is what TRT will never do.
- Full dynamic shape support: This is what TRT struggles at.
