### ISSUE TITLE
setup.py should not contain import of torch

### ISSUE THREAD

**Issue by jon-chuang** [chengzeyi/stable-fast#66]
If env e.g. docker has no installation of torch yet, this setup will fail.

Rather, torch should be imported lazily and the asserts performed only if torch is available

**Comment by chengzeyi** [comment]
> If env e.g. docker has no installation of torch yet, this setup will fail.
> 
> Rather, torch should be imported lazily and the asserts performed only if torch is available

That cannot be achieved. Since `stable-fast` in fact is a `CUDAExtension` of `torch`, it must require torch to build. So torch must be installed at first, then `stable-fast`😊.

**Comment by jon-chuang** [comment]
Yes. Indeed. Actually, the issue is that I can't seem to download the right whl, as I'm using torch nightly, whereas stable-fast wants torch.2.1, so it downloads the source code, thus running into this issue.

Is there any way I can force to use the whl?

**Comment by jon-chuang** [comment]
Ok, I can just `pip install https://github.com/chengzeyi/stable-fast/releases/download/v0.0.13.post3/stable_fast-0.0.13.post3+torch210cu121-cp310-cp310-manylinux2014_x86_64.whl`
