### ISSUE TITLE
Is there a way to save the compiled model to reduce loading time?

### ISSUE THREAD

**Issue by MuhammadArham-Vyro** [chengzeyi/stable-fast#7]

**Comment by chengzeyi** [comment]
Saving such a runtime compiled model is almost impossible. But there are still ways to reduce loading time.

Let's split the loading time into three parts: `TorchScript` compilation and passes, `Triton` compilation, and CUDA Graph Capture.

`TorchScript` compilation should be fast. But when the model is invoked at the first time, by default the `nvfuser` codegen fusion engine provided by the TorchScript interpreter will be activated and spend a lot of time generating CUDA kernels that will improve the overall performance by a small amount. So if you really care about the loading time, you could disable `nvfuser`.

`Triton` compilation includes kernel auto-tuning so each time the size of the image changes the recompilation will be triggered and each new process will need recompilation, too. But if you can keep the process running and use this single process to load different weights, the recompilation should not be triggered.

`CUDA Graph` Capture just needs to invoke a subgraph of the model several times. So its time should be not very long. But it can still be disabled to reduce loading time.

**Comment by chengzeyi** [comment]
> @chengzeyi how to disable nvfuser?

@jon-chuang See here: https://github.com/chengzeyi/stable-fast/blob/main/doc/troubleshooting.md
