### ISSUE TITLE
Does xformers still matter?

### ISSUE THREAD

**Issue by oxysoft** [chengzeyi/stable-fast#71]
Hi, I was wondering since you have done extensive benchmarking you probably have details on this. It seems that you have built-in support for xformers in there, but I thought pytorch 2.0 introduces an equivalent mechanism built-in? Should I still care about xformers? Cheers

**Comment by chengzeyi** [comment]
> Hi, I was wondering since you have done extensive benchmarking you probably have details on this. It seems that you have built-in support for xformers in there, but I thought pytorch 2.0 introduces an equivalent mechanism built-in? Should I still care about xformers? Cheers

It still matters. In stable-fast I patches diffusers to better utilize xformers' unique features which PyTorch's SDP does not support. That's the secret.

**Comment by oxysoft** [comment]
Worth mentioning in the README I'd say. Cheers!
