### ISSUE TITLE
SDXL Swap lora Issue

### ISSUE THREAD

**Issue by SuperSecureHuman** [chengzeyi/stable-fast#75]
Hey

I am trying to swap lora of the compiled model with the sample code given in readme. I get this error

![image](https://github.com/chengzeyi/stable-fast/assets/88489071/05a6c495-af4a-4289-929c-1b0a064e8661)

When I try to replace the weights myself, I am getting very bad outputs

My snippet of trying to swap weights

```
state_dict = pipe.unet.state_dict()
pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy_face")
update_state_dict(state_dict, pipe.unet.state_dict())
pipe.unet.load_state_dict(state_dict, assign=True)
```

Then infer.

**Comment by chengzeyi** [comment]
@SuperSecureHuman Try fusing lora before the compilation, and unfusing then refusing lora in each swap.
This functionality is tricky and I hope you understand the basic concept of CUDA memory management and CUDA Graph.

**Comment by SuperSecureHuman** [comment]
Got it, trying now

**Comment by chengzeyi** [comment]
If you cannot get it work, try disabling CUDA Graph and increasing the batch size to increase GPU utilization.

**Comment by chengzeyi** [comment]
And a LoRA may include other parts besides UNet. In such case, even text encoder and vae also need handling, and perhaps including other parts.

**Comment by SuperSecureHuman** [comment]
I'll try with my usecases, and getback if any help is needed with those componenets.

Thanks!
