### ISSUE TITLE
Problem with SDXL compilation

### ISSUE THREAD

**Issue by tg-bomze** [chengzeyi/stable-fast#8]
Hi. Thanks for the great repo. Tested it on SD1.5, the speed increase is really impressive. However, there are problems with SDXL. I'm trying to run it in Google Colab. Here's what I'm doing:

```python
!pip install -q diffusers transformers accelerate omegaconf ninja
!pip install -q https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-linux_x86_64.whl
!pip install -q https://download.pytorch.org/whl/triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
!pip install -q https://download.pytorch.org/whl/cu118/xformers-0.0.22.post4%2Bcu118-cp310-cp310-manylinux2014_x86_64.whl
!pip install -q https://github.com/camenduru/stable-fast/releases/download/colab/stable_fast-0.0.2-cp310-cp310-linux_x86_64.whl
```
next init and compile model
```python
from sfast.compilers.stable_diffusion_pipeline_compiler import (compile, CompilationConfig)
from diffusers import DiffusionPipeline
import torch, xformers, triton

torch.backends.cuda.matmul.allow_tf32 = True
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True).to("cuda")

config = CompilationConfig.Default()
config.enable_xformers = True
config.enable_triton = True
config.enable_cuda_graph = True
compiled_pipe = compile(pipe, config)
```
I end up trying to run an inference
```python
prompt = 'a car'
h, w = 1024, 1024
steps = 30
seed = 42
guidance_scale = 7
num_images = 1

image = pipe(
    prompt = prompt,
    height = h,
    width = w,
    num_inference_steps = steps,
    guidance_scale = guidance_scale,
    num_images_per_prompt = num_images,
    generator = torch.Generator(device='cuda').manual_seed(seed),
).images
```
I get the following error
```python
[/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py](https://localhost:8080/#) in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit, example_inputs_is_kwarg, _store_inputs)
   1063             else:
   1064                 example_inputs = make_tuple(example_inputs)
-> 1065                 module._c._create_method_from_trace(
   1066                     method_name,
   1067                     func,

RuntimeError: Tracer cannot infer type of BaseModelOutputWithPooling(last_hidden_state=tensor([[[-0.3884,  0.0229, -0.0523,  ..., -0.4902, -0.3066,  0.0674],

...

device='cuda:0', dtype=torch.float16)), attentions=None)
:Dictionary inputs to traced functions must have consistent type. Found Tensor and Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]
```

**Comment by chengzeyi** [comment]
> ```python
> BaseModelOutputWithPooling
> ```

This should be a bug with JIT trace. I would inspect soon.

**Comment by chengzeyi** [comment]
Hi, friend. Unfortunately, international network connection in my country is really slow and unstable and downloading large models like SDXL from HuggingFace Hub is painful. I would try my best to find ways to do experiments with it but it might take quite a while to get started.

**Comment by chengzeyi** [comment]
> Hi. Thanks for the great repo. Tested it on SD1.5, the speed increase is really impressive. However, there are problems with SDXL. I'm trying to run it in Google Colab. Here's what I'm doing:
> 
> ```python
> !pip install -q diffusers transformers accelerate omegaconf ninja
> !pip install -q https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-linux_x86_64.whl
> !pip install -q https://download.pytorch.org/whl/triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
> !pip install -q https://download.pytorch.org/whl/cu118/xformers-0.0.22.post4%2Bcu118-cp310-cp310-manylinux2014_x86_64.whl
> !pip install -q https://github.com/camenduru/stable-fast/releases/download/colab/stable_fast-0.0.2-cp310-cp310-linux_x86_64.whl
> ```
> 
> next init and compile model
> 
> ```python
> from sfast.compilers.stable_diffusion_pipeline_compiler import (compile, CompilationConfig)
> from diffusers import DiffusionPipeline
> import torch, xformers, triton
> 
> torch.backends.cuda.matmul.allow_tf32 = True
> pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True).to("cuda")
> 
> config = CompilationConfig.Default()
> config.enable_xformers = True
> config.enable_triton = True
> config.enable_cuda_graph = True
> compiled_pipe = compile(pipe, config)
> ```
> 
> I end up trying to run an inference
> 
> ```python
> prompt = 'a car'
> h, w = 1024, 1024
> steps = 30
> seed = 42
> guidance_scale = 7
> num_images = 1
> 
> image = pipe(
>     prompt = prompt,
>     height = h,
>     width = w,
>     num_inference_steps = steps,
>     guidance_scale = guidance_scale,
>     num_images_per_prompt = num_images,
>     generator = torch.Generator(device='cuda').manual_seed(seed),
> ).images
> ```
> 
> I get the following error
> 
> ```python
> [/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py](https://localhost:8080/#) in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit, example_inputs_is_kwarg, _store_inputs)
>    1063             else:
>    1064                 example_inputs = make_tuple(example_inputs)
> -> 1065                 module._c._create_method_from_trace(
>    1066                     method_name,
>    1067                     func,
> 
> RuntimeError: Tracer cannot infer type of BaseModelOutputWithPooling(last_hidden_state=tensor([[[-0.3884,  0.0229, -0.0523,  ..., -0.4902, -0.3066,  0.0674],
> 
> ...
> 
> device='cuda:0', dtype=torch.float16)), attentions=None)
> :Dictionary inputs to traced functions must have consistent type. Found Tensor and Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]
> ```

Good news, friend!

I am very pleased to inform you that SDXL is now supported in the latest release.

Check out the `README` to see how it works!

**Comment by chengzeyi** [comment]
@tg-bomze 

Good news, friend!

I am very pleased to inform you that SDXL is now supported in the latest release.

Check out the `README` to see how it works!

**Comment by tg-bomze** [comment]
> @tg-bomze
> 
> Good news, friend!
> 
> I am very pleased to inform you that SDXL is now supported in the latest release.
> 
> Check out the `README` to see how it works!

Thanks a lot, man. That's really cool news. I'm gonna test it out today.
