### ISSUE TITLE
Is it possible to optimize ControlNet while retaining dynamic strength?

### ISSUE THREAD

**Issue by oxysoft** [chengzeyi/stable-fast#82]
Hi, I was confused at first why applying stable-fast made my application much slower than without, and it took me a while to realize that changing the strength of the ControlNet leads to a recompilation of some sort every time. (audio-reactive animation, the strength changes every frame) Is there a way we could still optimize ControlNet to some extent without this limitation? If not, I suggest adding a flag to disable ControlNet compilation, as I had to comment out ControlNet compilation. I also recommend clearly indicating on the front page a list of the parameters which result in a recompilation, as it was quite unexpected for me.

Cheers!

**Comment by chengzeyi** [comment]
@oxysoft Hey, oxysoft.

Refusing recompilation when some `int/float/bool` arguments change is not possible.

However, you can compile some submodules of the pipeline individually. For example, there are two functions called `compile_unet` and `compile_vae` in the same Python module as `compile`. So just import them and invoke them on the `unet` and `vae` of your pipeline.
