### ISSUE TITLE
Is it possible to use this for multiple aspect ratios? Is there a way to decrease graph creation time during first inference when using dynamic shapes?

### ISSUE THREAD

**Issue by MuhammadArham-Vyro** [chengzeyi/stable-fast#9]
I am using the Stable-Fast compilation to use SD2.1 models for multiple aspect ratios. It takes about 50 seconds to infer on each size and then speeds up inference. 

Is there a way to speed up the process?

**Comment by chengzeyi** [comment]
To reduce compilation overhead, you could disable the optimization execution of TorchScript to avoid JIT kernel generation and disable CUDA graph feature.

Triton autotune might also be slow so you could disable triton, but that might significantly slow down inference.

```python3
config.enable_triton = False
config.enable_cuda_graph = False

compiled_model = compile(model, config)

with torch.jit.optimized_execution(False):
    # call model here
    # ...
```
