### ISSUE TITLE
Can Dynamically Switch LoRA support text_encoder?

### ISSUE THREAD

**Issue by Hap-Zhang** [chengzeyi/stable-fast#95]
Hi, zeyi
Thank you for your great repo for sd. Our lora adapter not only for unet but also text_encoder, and the example of dynamic switch lora is for unet only. Can dynamically switch lora support text_encoder lora adapter? How can I modify it?Looking forward to your reply.

**Comment by chengzeyi** [comment]
@Hap-Zhang Yes, it should.
