### ISSUE TITLE
How to avoid the long time required for the first warm up after compile the model

### ISSUE THREAD

**Issue by wz0424** [chengzeyi/stable-fast#98]
The acceleration of sfast performs very well, but the first warm up takes a bit too long. If I need to switch between different models frequently, it will take a very long time on warm up, is there any way to avoid this problem?
<img width="711" alt="image" src="https://github.com/chengzeyi/stable-fast/assets/51048934/6a9dc175-3394-4e45-a739-4bb364bc43de">

**Comment by chengzeyi** [comment]
@wz0424 @Hap-Zhang See https://github.com/chengzeyi/stable-fast/blob/main/doc/troubleshooting.md#compilation-is-so-slow-how-to-improve-it
